import { supabase } from "./supabase";

async function setupReactionsTable() {
  // Create the reactions table
  const { error: createError } = await supabase.rpc("create_reactions_table", {
    sql: `
      create table if not exists public.reactions (
        id bigint generated by default as identity primary key,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null,
        emoji text not null,
        count integer default 1 not null
      );

      -- Set up Row Level Security (RLS)
      alter table public.reactions enable row level security;

      -- Allow public read access
      create policy if not exists "Allow public read access on reactions"
        on public.reactions
        for select
        to public
        using (true);

      -- Allow public insert/update
      create policy if not exists "Allow public insert/update on reactions"
        on public.reactions
        for all
        to public
        using (true)
        with check (true);
    `,
  });

  if (createError) {
    console.error("Error creating reactions table:", createError);
    return;
  }

  console.log("Reactions table created successfully!");
}

// Run the setup
setupReactionsTable();
